[theme]
primaryColor = "#6CA0DC"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#181b20"
textColor = "#fafafa"
font = "Montserrat, sans-serif"

[[theme.fontFaces]]
family = "Montserrat"
src = "url('https://fonts.gstatic.com/s/montserrat/v25/JTUQjIg1_i6t8kCHKm459WxhzA.woff2')"
