[theme]
primaryColor = "#6CA0DC"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#181b20"
textColor = "#fafafa"
font = "Roboto, sans-serif"

[[theme.fontFaces]]
family = "Roboto"
src = "url('https://fonts.gstatic.com/s/roboto/v30/KFOmCnqEu92Fr1Mu4mxM.woff2')"
